/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fox.gltf 
Author: Vlad Zaichyk (https://sketchfab.com/vladzaichyk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-fox-01674a892f414c0681afdeb563cc8e13
Title: Lowpoly fox
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/fox.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Fox_by_vladhad22@gmailcom_0'].geometry} material={materials['Material.001']} position={[0.56, -2.475, 1.051]} rotation={[0.06, -0.026, -0.102]} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.002']} scale={8.404} />
        <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.Material} position={[0.226, 6.994, 0.63]} rotation={[0, 0, -1.07]} scale={0.905} />
        <mesh geometry={nodes.Icosphere_0.geometry} material={materials['Material.003']} position={[1.065, 8.218, 7.473]} scale={[6.285, 6.285, 3.583]} />
        <mesh geometry={nodes.Icosphere001_0.geometry} material={materials['Material.007']} position={[-69.608, 16.053, 18.229]} scale={5.95} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.009']} position={[-30.238, 20.068, -0.925]} rotation={[0, 0, 0.585]} scale={9.607} />
      </group>
    </group>
  )
}

useGLTF.preload('/fox.gltf')
